### ISSUE TITLE
在github自动构建插件

### ISSUE THREAD

**Issue by wykwey** [Encinet/OceanBot#1]
在github自动构建插件 本地构建太慢了

**Comment by ObcbO** [comment]
?! 这个项目居然有人注意到
目前这个插件还是不能正常启动的，所以短时间内还是不会有大动作（因为在把miraimc依赖移除更换到mirai-core卡壳了）
不过还是感谢你的建议

**Comment by ObcbO** [comment]
目前能正常启动了(main分支) 但是deviceinfo和一些功能处于关闭状态(为了测试)

**Comment by ObcbO** [comment]
已可以自动构建
